config_version = 1

# Place your real config next to the app (same folder):
#   ./config.toml
# Copy this file there and edit the values to match your setup.

update_interval_ms = 500      # How often to send REST updates (tweak for performance).
default_transition_ms = 150   # Crossfade time for REST updates to smooth changes.
debug = true
gaming_preset = "Gaming"      # Default preset to use when a game starts (per-controller override below).



[notification]
duration = 2
font = "Alegreya Sans SC"
fontsize = 33
fontcolour = "#FFFFFF"
padding = 15
bodycolour = "#000000"
bodyopacity = 10
border = 0
align = "topcenter"

[mqtt]
host = "192.168.20.80"
port = 1883
username = "mqtt"
password = "pi3.14159"
tls = false
topic = "runlights/notify"

[[controllers]]
id = "PCROOMLHS"
friendlyname = "PC Room Left Shelf"
host = "192.168.20.118"
gaming_preset = "Gaming"

  [[controllers.segments]]
  id = 0
  label = "microbee"
  friendlyname = "Microbee"

  [[controllers.segments]]
  id = 1
  label = "amiga"
  friendlyname = "Commodore Amiga 1200"

  [[controllers.segments]]
  id = 2
  label = "atari"
  friendlyname = "Atari 2600"

  [[controllers.segments]]
  id = 3
  label = "n64"
  friendlyname = "Nintendo 64"

  [[controllers.segments]]
  id = 4
  label = "snes"
  friendlyname = "Super Nintendo"

  [[controllers.segments]]
  id = 5
  label = "nes"
  friendlyname = "Nintendo Entertainment System"

[[controllers]]
id = "PCROOMRHS"
friendlyname = "PC Room Right Shelf"
host = "192.168.20.245"
gaming_preset = "Gaming"

  [[controllers.segments]]
  id = 0
  label = "c64"
  friendlyname = "Commodore 64"

  [[controllers.segments]]
  id = 1
  label = "dreamcast"
  friendlyname = "PC Room Right Shelf"

  [[controllers.segments]]
  id = 2
  label = "saturn"
  friendlyname = "saturn"

  [[controllers.segments]]
  id = 3
  label = "megadrive"
  friendlyname = "Mega Drive"

  [[controllers.segments]]
  id = 4
  label = "gamegear"
  friendlyname = "Game Gear"

  [[controllers.segments]]
  id = 5
  label = "mastersystem"
  friendlyname = "Master System"

[[controllers]]
id = "PCROOMMIDDLE"
friendlyname = "PC Room Middle"
host = "192.168.20.182"
gaming_preset = "Gaming"

  [[controllers.segments]]
  id = 0
  label = "steam"
  friendlyname = "Steam"

# Applications and their modes
[[application]]
id = "quake1"
friendlyname = "Quake"
processes = ["glqwcl.exe"]

  [[application.modes]]
  id = "health"
  input = "screen_region"
  output = "crossfade"
  acolor = "#ffe5d0"
  abrightness = "128"
  bcolor = "#ffffff"
  bbrightness = "255"
  rangelow = 0
  rangehigh = 250
  x = 140
  y = 458
  width = 100
  height = 200
  controllers = ["PCROOMLHS"]

  [[application.modes]]
  id = "ammo"
  input = "screen_region"
  output = "crossfade"
  acolor = "#ffe5d0"
  abrightness = "255"
  bcolor = "#ffff00"
  bbrightness = "255"
  x = 1791
  y = 2018
  width = 59
  height = 32
  controllers = ["PCROOMRHS"]

[[application]]
id = "caretaker"
friendlyname = "The Last Caretaker"
processes = ["voyage.exe"]

  [[application.modes]]
  id = "health"
  input = "screen_region"
  output = "segmentpercent"
  acolor = "#ffffff"
  abrightness = "128"
  bcolor = "#ff0000"
  bbrightness = "128"
  delimiter = "/"
  minvalue = "1"
  maxvalue = "99"
  segmentorderreverse = true
  dangertype = "flash"
  dangerthreshold = "20"
  x = 1791
  y = 2084
  width = 59
  height = 32
  controllers = ["PCROOMLHS"]

  [[application.modes]]
  id = "power"
  input = "screen_region"
  output = "segmentpercent"
  acolor = "#FFFF00"
  abrightness = "128"
  bcolor = "#000000"
  bbrightness = "0"
  delimiter = "/"
  minvalue = "0"
  maxvalue = "500"
  segmentorderreverse = true
  dangertype = "flash"
  dangerthreshold = "20"
  x = 1791
  y = 2018
  width = 50
  height = 32
  controllers = ["PCROOMRHS"]

[[application]]
id = "starrapture"
friendlyname = "StarRupture"
processes = ["StarRuptureGameSteam.exe"]

  [[application.modes]]
  id = "health"
  input = "screen_region"
  output = "segmentpercent"
  acolor = "#ffffff"
  abrightness = "128"
  bcolor = "#ff0000"
  bbrightness = "128"
  minvalue = "1"
  maxvalue = "99"
  segmentorderreverse = true
  dangertype = "flash"
  dangerthreshold = "20"
  x = 645
  y = 1911
  width = 70
  height = 42
  controllers = ["PCROOMLHS"]

  [[application.modes]]
  id = "power"
  input = "screen_region"
  ocr_color = "red"
  ocr_contrast = 1.0
  output = "segmentpercent"
  acolor = "#FFFFFF"
  abrightness = "128"
  bcolor = "#FFFFFF"
  bbrightness = "0"
  delimiter = "/"
  minvalue = "0"
  maxvalue = "50"
  segmentorderreverse = true
  dangertype = "flash"
  dangerthreshold = "20"
  x = 645
  y = 1841
  width = 60
  height = 40
  controllers = ["PCROOMRHS"]

[[application]]
id = "esde"
friendlyname = "Emulation Station Desktop Edition"
processes = ["ES-DE.exe"]

  [[application.modes]]
  id = "game-select"
  input = "CLI"
  output = "segmentsolid"
  acolor = "#ffe5d0"
  abrightness = "255"
  bcolor = "#000000"
  bbrightness = "0"
  controllers = ["PCROOMLHS", "PCROOMRHS","PCROOMMIDDLE"]

  [application.modes.bindings]
  amiga = { controller = "PCROOMLHS", segment = 1 }
  atari2600 = { controller = "PCROOMLHS", segment = 2 }
  n64 = { controller = "PCROOMLHS", segment = 3 }
  snes = { controller = "PCROOMLHS", segment = 4 }
  nes = { controller = "PCROOMLHS", segment = 5 }
  c64 = { controller = "PCROOMRHS", segment = 0 }
  dreamcast = { controller = "PCROOMRHS", segment = 1 }
  saturn = { controller = "PCROOMRHS", segment = 2 }
  megadrive = { controller = "PCROOMRHS", segment = 3 }
  gamegear = { controller = "PCROOMRHS", segment = 4 }
  mastersystem = { controller = "PCROOMRHS", segment = 5 }
  steam = { controller = "PCROOMMIDDLE", segment = 0 }
  







[[application]]
id = "doomdarkages"
friendlyname = "Doom The Dark Ages"
processes = ["DOOMTheDarkAges.exe"]

  [[application.modes]]
  id = "armor"
  input = "screen_region"
  output = "fade"
  x = 1060
  y = 1320
  width = 100
  height = 60
  controllers = ["PCROOMLHS"]
  minvalue = 0.0
  maxvalue = 255.0
  acolor = "#0000ff"
  abrightness = 0
  bbrightness = 255

  [[application.modes]]
  id = "health"
  input = "screen_region"
  output = "fade"
  x = 1396
  y = 1320
  width = 100
  height = 60
  interval_ms = 500
  inputrangemin = 0.0
  inputrangemax = 100.0
  controllers = ["PCROOMRHS"]
  minvalue = 0.0
  maxvalue = 255.0
  acolor = "#aa0000"
  abrightness = 0
  bbrightness = 255

